server:
  port: 8084

spring:
  application:
    name: ms-inventario
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/inventariodb
    username: admin
    password: admin123
    jpa:
      hibernate:
        ddl-auto: update
      database: PostgreSQL
      database-platform: org.hibernate.dialect.PostgreSQLDialect