server:
  port: 8088

spring:
  application:
    name: ms-reporte
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/reportedb
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka