server:
  port: 8087

spring:
  application:
    name: ms-sales
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/salesdb
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

sunat:
  api:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhYmxvY2ZyMjJAZ21haWwuY29tIn0.4uhdCdLKQSUTX0Q0IKrUvkALxNdskd6tdiz8V5HjZPc