server:
  port: 8086

spring:
  application:
    name: ms-seguridad
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/keycloackdb
    username: admin
    password: admin123
    jpa:
      hibernate:
        ddl-auto: update
      database: PostgreSQL
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/keycloack-libreria