create table ventas
(
	venta_id uuid not null
		primary key,
	activo boolean not null,
	cliente_id uuid,
	codigo varchar(255),
	estado varchar(255)
		constraint ventas_estado_check
			check ((estado)::text = ANY ((ARRAY['CONFIRMADO'::character varying, 'PENDIENTE'::character varying, 'CANCELADO'::character varying])::text[])),
	fecha_venta date,
	total double precision
);

create table detalle_ventas
(
	id integer generated by default as identity
		primary key,
	cantidad integer,
	precio_unitario double precision,
	producto_id uuid,
	subtotal double precision,
	venta_id uuid not null
		constraint fk2dn1sdhrbmva44wbs9fy6l7mn
			references ventas
);

create table facturas
(
	facturacion_id uuid not null
		primary key,
	activo boolean not null,
	estado varchar(255),
	fecha_factura date,
	impuestos double precision,
	metodo_pago varchar(255),
	numero_factura varchar(255),
	subtotal double precision,
	total double precision,
	venta_id uuid not null
		constraint fk5od6qepbdy770aby1hqrtffe0
			references ventas
);

create table detalle_facturas
(
	id integer generated by default as identity
		primary key,
	cantidad integer,
	descripcion varchar(255),
	subtotal double precision,
	valor_unitario double precision,
	facturacion_id uuid not null
		constraint fkns8mo1vk4u28nhg15o4bc6p81
			references facturas
);

create table pagos
(
	pago_id integer generated by default as identity
		primary key,
	activo boolean not null,
	estado varchar(255),
	fecha_pago date,
	metodo_pago varchar(255),
	monto double precision,
	venta_id uuid not null
		constraint fkr2gojgwqy0othfw6qnrncedj3
			references ventas
);


